---
queue_rules:
  - name: queue_jenkins
    queue_conditions:
      - check-success=jenkins_check
    merge_conditions:
      - label=not_set_wont_merge

pull_request_rules:
  - name: queue_pull_request
    conditions:
      - base=main
    actions:
      queue:
