---
version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins-local
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "jenkins_home:/var/jenkins_home"
    restart: on-failure

volumes:
  jenkins_home:
